name: Release

on:
  push:
    branches:
      - main

env:
  COREPACK_DEFAULT_TO_LATEST: 0

permissions: {}

jobs:
  release:
    name: Publish
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Set up pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure Git
        run: |
          git config --global user.email 34733141+seek-oss-ci@users.noreply.github.com
          git config --global user.name 'Github changeset workflow'

      - name: Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run stage
          setupGitUser: false
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
